[project]
name = "nnue-pytorch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asciimatics>=1.15.0",
    "cupy-cuda12x>=13.4.1",
    "gputil>=1.4.0",
    "matplotlib>=3.10.3",
    "numba>=0.61.2",
    "numpy>=2",
    "psutil>=7.0.0",
    "python-chess==0.31.4",
    "lightning>=2.5",
    "tensorboard>=2.19.0",
    "torch>=2.7.0",
    "jsonargparse[signatures]>=4.27"
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
